### ISSUE TITLE
Where to download the dataset described in your paper? Are they all publicly available?(I open the link provided in your paper but can not find the download link)

### ISSUE THREAD

**Issue by brisker** [mp2893/med2vec#1]
Where to download the dataset described in your paper? Are they all publicly available?

**Comment by mp2893** [comment]
The dataset from Children's Healthcare of Atlanta is not publicly available.
CMS dataset, which was used in the paper, is synthetic but large in volume. You can download it [here](https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SynPUFs/index.html).
MIMIC3 is a publicly available deidentified dataset, which consists of real ICU patients. You can download it [here](https://mimic.physionet.org/gettingstarted/access/).
