### ISSUE TITLE
Questions about experiments

### ISSUE THREAD

**Issue by x12346x12346x** [mp2893/med2vec#12]
Hello, thank you for your code available.
You mentioned about two experiments in your paper, but actually, I don't understand how to do these experiments.
Could you please tell me how to do these experiments clearly?
Thank you!

**Comment by mp2893** [comment]
Hi, 
Discussing the paper here will be out of focus.
If you are really interested in the experiments, we could chat separately.
Please send me an email to mp2893@gmail.com

Best,
Ed
