### ISSUE TITLE
questions about the training data format

### ISSUE THREAD

**Issue by vpccw152c** [mp2893/med2vec#13]
hi there, thanks a lot for making the code available, it helps me a lot to understand you paper.
I have a question about the format of training data. In README.md, step 3, when describing how to prepare the training data, each visit is said to be represented by a list of integers, such as [5,8,13]. In the closed issue "'output file" (https://github.com/mp2893/med2vec/issues/7), you answered TheodoreZhao's question, and said that "For visit representation, you can derive the code-level representation using u_t = ReLU(W_emb x_t + b_emb), possibly with a multi-hot vector, then use v_t = ReLU(W_hidden u_t + b_hidden) to derive the visit representation ".

so my question is, if I represent a visit with a list of integers in the training step, and compute a visit representation based on a multi-hot vector, what's the relationship between the list and the multi-hot vector? how to get the multi-hot vector for each visit?

thanks.

**Comment by mp2893** [comment]
Hi, 
The list of integers (e.g. [3, 5, 2]) can be transformed into a multi-hot vector (e.g. [0, 0, 1, 1, 0, 1, 0, 0, ...]). The dimensionality of the multi-hot vector is equivalent to the number of unique codes in your data.

Thanks,
Ed

**Comment by vpccw152c** [comment]
Hi there, sorry to bother you again, but I wonder weather med2vec could handle a situation where each patient has only one visit, namely the trainings data is in the form of, for example, [[2,5,8],[-1],[6,9,23],[-1],[7,9,21]], since in the examples you give in README, each patient has at least two visits.
Thanks a lot for your responses

**Comment by mp2893** [comment]
In that case, med2vec won’t be trained properly because there are no neighboring visits to predict.
