### ISSUE TITLE
Negative Code Embeddings

### ISSUE THREAD

**Issue by Ankit267** [mp2893/med2vec#17]
Hello Ed,

In the Med2Vec code , you have mentioned the weights as (-0.01,0.01) ,which is generating negative code embeddings.
_params['W_emb'] = np.random.uniform(-0.01, 0.01_,

however in the paper you have mentioned that "all medical codes C to **non-negative** real-valued vectors of dimension m"

Can you please help me in understanding that?

Thanks,
Ankit

**Comment by mp2893** [comment]
Hi Ankit,

Medical codes are derived by ReLU(W_emb x_t + b_emb), which makes the codes non-negative.
(That is the equation (1) in the paper).

Best,
Ed

**Comment by Virtusa-vLife** [comment]
OKay ...thanks.

**Comment by Ankit267** [comment]
Thanks Ed!!
