### ISSUE TITLE
Mapping embeddings to ICD codes

### ISSUE THREAD

**Issue by pooja01** [mp2893/med2vec#21]
Hi Dr. Choi,

Thank you for sharing your work on Github!

Could you please tell me where I find the mapping between the ICD codes and the embeddings? I was testing med2vec on demo MIMIC data and W_emb is an array of dimensions 4894*200, where 4894 are the unique ICD codes, could you please let me know where I can find the mapping between W_emb and the corresponding ICD code names?

Thanks a lot!

**Comment by mp2893** [comment]
After you run process_mimic.py, you will get 4 output files.
The ones that end with *.types is the Python Dictionary where the mappings are stored.
Best,
Ed

**Comment by pooja01** [comment]
Thank you! I appreciate your quick response.
