### ISSUE TITLE
GPU training fails

### ISSUE THREAD

**Issue by tRosenflanz** [mp2893/med2vec#5]
I am getting an error when trying to do the training on the GPU. There are 47108 unique codes (quite a lot more than in the Mimic) but I am still getting an error even if I am using code and visit representations of just 5 dimensions and batch size of just 1 so I don't believe it is an out of memory problem. That is of course if my math is right: 
2 Dense vectors of 47108 doubles: just 1 mb 
47108x5 matrix for Dense to Code representation: 2 mb
5x5 matrix for Code represnetation to Visit: 200 bytes

Any help will be appreciated!

> Using gpu device 0: Tesla P100-SXM2-16GB (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5110)
initializing parameters
building models
loading data
training start
[[ 0.  0.  0. ...,  0.  0.  0.]]
Traceback (most recent call last):
  File "med2vec.py", line 323, in <module>
    train_med2vec(seqFile=args.seq_file, demoFile=args.demo_file, labelFile=args.label_file, outFile=args.out_file, numXcodes=args.n_input
_codes, numYcodes=args.n_output_codes, embDimSize=args.cr_size, hiddenDimSize=args.vr_size, batchSize=args.batch_size, maxEpochs=args.n_ep
och, L2_reg=args.L2_reg, demoSize=args.demo_size, windowSize=args.window_size, logEps=args.log_eps, verbose=args.verbose)
  File "med2vec.py", line 290, in train_med2vec
    cost = f_grad_shared(x, mask, iVector, jVector)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
RuntimeError: Cuda error: GpuElemwise node_ea5fafbdcfd074e674342684e5c33a10_0 Exp: an illegal memory access was encountered.
    n_blocks=30 threads_per_block=256
   Call: kernel_Exp_node_ea5fafbdcfd074e674342684e5c33a10_0_Ccontiguous<<<n_blocks, threads_per_block>>>(numEls, i0_data, o0_data)
Apply node that caused the error: GpuElemwise{Exp}[(0, 0)](GpuDot22.0)
Toposort index: 35
Inputs types: [CudaNdarrayType(float32, matrix)]
Inputs shapes: [(47108, 47108)]
Inputs strides: [(47108, 1)]
Inputs values: ['not shown']
Outputs clients: [[GpuCAReduce{add}{0,1}(GpuElemwise{Exp}[(0, 0)].0), GpuElemwise{Mul}[(0, 1)](GpuDimShuffle{0,x}.0, GpuElemwise{Exp}[(0,
0)].0)]]

Edit: I also checked that 47108 codes do not cause problems by using only 10 codes and adding `x[idx][np.array(seq)%numXcodes] = 1. ` in padMatrix

**Comment by mp2893** [comment]
Hi tRosenflanz,

Thank you for your interest in our work.
According to your error log, it doesn't seem to be an out-of-memory problem.
The code is basically trying to access some tensor at an index out of its boundary.
Would you check if your training/testing data construction was correct?
(e.g. maybe you are using 1-based indexing instead of 0-based indexing?)

Thanks,
Ed

**Comment by tRosenflanz** [comment]
Hi Ed, 

I checked - I use 0 based indexing. Here is an error log with exception_verbosity=high. Interesting part is Constant{-1} followed by an error in the CudaNdarrayConstant:
```

  - b_emb_rgrad2, Shared Input, Shape: (200,), ElemSize: 4 Byte(s), TotalSize: 800 Byte(s)
 - b_hidden_rgrad2, Shared Input, Shape: (200,), ElemSize: 4 Byte(s), TotalSize: 800 Byte(s)
 - Elemwise{Cast{int64}}.0, Shape: (6,), ElemSize: 8 Byte(s), TotalSize: 48 Byte(s)
 - Elemwise{Cast{int64}}.0, Shape: (6,), ElemSize: 8 Byte(s), TotalSize: 48 Byte(s)
 - jVector, Input, Shape: (6,), ElemSize: 4 Byte(s), TotalSize: 24 Byte(s)
 - GpuElemwise{Exp}[(0, 0)].0, Shape: (6,), ElemSize: 4 Byte(s), TotalSize: 24 Byte(s)
 - iVector, Input, Shape: (6,), ElemSize: 4 Byte(s), TotalSize: 24 Byte(s)
 - Constant{1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{-1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - GpuCAReduce{add}{1,1}.0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - GpuElemwise{Add}[(0, 1)].0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - GpuCAReduce{add}{1,1}.0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - mask, Input, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - CudaNdarrayConstant{error while transferring the value: error (an illegal memory access was encountered)copying data to host}, Shape: (
1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - GpuElemwise{add,no_inplace}.0, Shape: (0, 47108), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 - GpuElemwise{mul,no_inplace}.0, Shape: (0, 47108), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 - GpuSubtensor{:int64:}.0, Shape: (0, 47108), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 - GpuDimShuffle{0,x}.0, Shape: (0, 1), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 - GpuElemwise{mul,no_inplace}.0, Shape: (0, 47108), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 - GpuDimShuffle{0,x}.0, Shape: (0, 1), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 - GpuElemwise{add,no_inplace}.0, Shape: (0, 47108), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 - GpuSubtensor{int64::}.0, Shape: (0, 47108), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 - GpuElemwise{sub,no_inplace}.0, Shape: (0, 47108), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 - GpuElemwise{sub,no_inplace}.0, Shape: (0, 47108), ElemSize: 4 Byte(s), TotalSize: 0 Byte(s)
 TotalSize: 9142276336.0 Byte(s) 8.514 GB
 TotalSize inputs: 227357052.0 Byte(s) 0.212 GB
```

**Comment by tRosenflanz** [comment]
So I created a toy dataset: 
```

lens=[np.random.randint(1,10) for x in range(1000)]
data=[list(np.random.randint(0,10,size=x,dtype=int)) if x>1 else [-1] for x in lens ]
```
And started trying different values for <n_input_codes> and it breaks at around 47000. I am thinking that this is due to Tensor with shape 47000,47000 which would make sense since 47000^2 * 4(bytes) * 2(data+gradient) ~16gb which overflows the memory

**Comment by tRosenflanz** [comment]
I think this issue can be closed - I recreated the original dataset with less codes by grouping some of them together. Total number of codes is now 33000 which works just fine and trains decently well

**Comment by mp2893** [comment]
Thanks for the important info.
I never had this problem because my dataset had less than 40K unique codes.
I will add this to the readme.

Best,
Ed
