### ISSUE TITLE
Output model/weights?

### ISSUE THREAD

**Issue by ddofer** [mp2893/med2vec#8]
Hi, I read your paper and wanted to ask if the trained (on MIMIC-III) model/W2V can be downloaded directly - I'd like to see and to try it on our internal medical data before setting up resources to try to train a new model. (And training a new model from scratch would take weeks - It's a common practice to share the base model).

thanks!

**Comment by mp2893** [comment]
Hi Dan,

I don't have the trained model of MIMIC-III, but I do have the trained model of a large private dataset.
You can find it at the bottom of [my personal webpage](http://mp2893.com) under the subsection "Healthcare Concept Representation Learned by Med2Vec".
Hope this helps.

Thanks,
Ed

**Comment by ddofer** [comment]
Thanks!
Any special preprocessing of the icd 9 codes?

**Comment by mp2893** [comment]
No that model uses full 5-digit ICD code.
